In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

## Create and Read esc + m + shift + enter

#### 1D array

In [4]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(5,)

In [8]:
arr1

array([1, 2, 3, 4, 5])

In [9]:
arr1.ndim

1

In [10]:
arr1.size

5

In [12]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr2.ndim #give dimension of the array

2

In [14]:
arr2.shape #(rows,colums)

(2, 3)

In [15]:
arr2.dtype

dtype('int64')

In [16]:
arr2.size

6

In [22]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,2,9]],[[7,8,9],[4,2,9]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [4, 2, 9]],

       [[7, 8, 9],
        [4, 2, 9]]])

In [23]:
arr3.shape

(3, 2, 3)

In [24]:
arr3.ndim

3

In [27]:
arr3.size

18

###Create Random Array  

In [29]:
randomArr=np.random.rand(3,2,3)
randomArr

array([[[0.03623967, 0.40264496, 0.03353441],
        [0.71118708, 0.51966953, 0.50765206]],

       [[0.01770936, 0.62846853, 0.8612876 ],
        [0.14569804, 0.06621794, 0.27764985]],

       [[0.82584558, 0.01091538, 0.24430635],
        [0.59686898, 0.12238389, 0.97991824]]])

In [30]:
randomArr.dtype

dtype('float64')

In [32]:
zeroes=np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
zeroes.ndim

3

In [34]:
full=np.full((3,2,3),7)
full

array([[[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]]])

In [35]:
ones=np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [36]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [4, 2, 9]],

       [[7, 8, 9],
        [4, 2, 9]]])

In [37]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr3[0][0]

array([1, 2, 3])

In [39]:
arr3[0][0][0]

np.int64(1)

In [40]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [4, 2, 9]],

       [[7, 8, 9],
        [4, 2, 9]]])

In [41]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr3[0:2]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [4, 2, 9]]])

In [43]:
arr3[-1]

array([[7, 8, 9],
       [4, 2, 9]])

In [45]:
arr3[1,0,2]

np.int64(9)

##Update and Delete

In [46]:
a1=np.random.rand(2, 3, 2)
a2=np.random.rand(2, 3, 2)

In [47]:
a1

array([[[0.65229988, 0.931707  ],
        [0.22515079, 0.57483948],
        [0.7340419 , 0.95220008]],

       [[0.26782666, 0.5627539 ],
        [0.95707537, 0.35954986],
        [0.96362051, 0.27902397]]])

In [48]:
a2

array([[[0.48158448, 0.57207755],
        [0.30981753, 0.85965885],
        [0.39201826, 0.178259  ]],

       [[0.15272854, 0.8605106 ],
        [0.9103063 , 0.1268464 ],
        [0.16203735, 0.31791831]]])

##Basic Maths

In [51]:
np.add(a1,a2)

array([[[1.13388436, 1.50378454],
        [0.53496832, 1.43449833],
        [1.12606016, 1.13045908]],

       [[0.42055521, 1.4232645 ],
        [1.86738167, 0.48639626],
        [1.12565785, 0.59694228]]])

In [52]:
np.subtract(a1,a2)

array([[[ 0.1707154 ,  0.35962945],
        [-0.08466674, -0.28481938],
        [ 0.34202364,  0.77394108]],

       [[ 0.11509812, -0.2977567 ],
        [ 0.04676907,  0.23270346],
        [ 0.80158316, -0.03889434]]])

In [53]:
np.divide(a1,a2)

array([[[1.35448693, 1.62863759],
        [0.72672062, 0.66868325],
        [1.87246865, 5.34166624]],

       [[1.75361238, 0.65397672],
        [1.05137729, 2.83452949],
        [5.94690381, 0.87765933]]])

In [54]:
np.multiply(a1,a2)

array([[[0.3141375 , 0.53300865],
        [0.06975566, 0.49416585],
        [0.28775783, 0.16973823]],

       [[0.04090478, 0.4842557 ],
        [0.87123174, 0.04560761],
        [0.15614251, 0.08870683]]])

##Statistical operrations

In [55]:
sqrt=np.sqrt(25)
abs=np.abs(-2)
power=np.power(2,8)
log=np.log(25)
mins=np.min(a1)
maxs=np.max(a2)

In [56]:
sqrt

np.float64(5.0)

In [57]:
abs

np.int64(2)

In [58]:
power

np.int64(256)

In [59]:
log

np.float64(3.2188758248682006)

In [60]:
mins

np.float64(0.22515078808525968)

In [61]:
maxs

np.float64(0.9103062970618049)

#Update

In [63]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [4, 2, 9]],

       [[7, 8, 9],
        [4, 2, 9]]])

In [64]:
arr3[0,0,2] = 345

In [65]:
arr3

array([[[  1,   2, 345],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [  4,   2,   9]],

       [[  7,   8,   9],
        [  4,   2,   9]]])

In [66]:
arr3.sort()

In [67]:
arr3

array([[[  1,   2, 345],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [  2,   4,   9]],

       [[  7,   8,   9],
        [  2,   4,   9]]])

In [70]:
#Reshape
arr3.shape

(3, 2, 3)

In [71]:
arr3_reshape=arr3.reshape(2,3,3)
arr3_reshape

array([[[  1,   2, 345],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  2,   4,   9],
        [  7,   8,   9],
        [  2,   4,   9]]])

In [72]:
arr3_reshape.shape

(2, 3, 3)

#Appending and Inserting

In [73]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [75]:
#Creating an new array
new_array=np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [76]:
appd=np.append(zeroes, new_array,axis=0) #axis 0= rows and axis 1 = colums

In [77]:
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

##INsert

In [78]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [80]:
inserted_array=np.insert(zeroes,1,ones, axis=0)

In [81]:
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

##Delete1m

In [84]:
arr4=np.random.rand(3,2,3)

In [85]:
arr4

array([[[0.51886787, 0.09304689, 0.41119154],
        [0.58439547, 0.5050291 , 0.02532696]],

       [[0.33828568, 0.70543275, 0.07591194],
        [0.14563219, 0.20943285, 0.78338342]],

       [[0.25881348, 0.70479464, 0.96871619],
        [0.62001518, 0.68273586, 0.1278759 ]]])

In [89]:
#delete the array
arr5=np.delete(arr4,0,axis=1)

In [90]:
arr5

array([[[0.58439547, 0.5050291 , 0.02532696]],

       [[0.14563219, 0.20943285, 0.78338342]],

       [[0.62001518, 0.68273586, 0.1278759 ]]])

In [91]:
np.save("new_array",arr5)

In [92]:
np.load("new_array.npy")

array([[[0.58439547, 0.5050291 , 0.02532696]],

       [[0.14563219, 0.20943285, 0.78338342]],

       [[0.62001518, 0.68273586, 0.1278759 ]]])